services:
  login-ms:
    build:
      context: ./login-ms
      dockerfile: Dockerfile
  register-ms:
    build:
      context: ./register-ms
      dockerfile: Dockerfile
  metadata-ms:
    build:
      context: ./metadata-ms
      dockerfile: Dockerfile

  metadata-db:
    image: cassandra:latest
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
